"trigger_API","trigger_package","API","package","related_package_version","error_type","error_description"
"imblearn.over_sampling.SMOTE","imblearn","sklearn.externals.six","sklearn","[{""package"": ""imbalanced-learn"", ""version"": ""0.4.3""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"imblearn.over_sampling.SMOTE","imblearn","sklearn.utils.safe_indexing","sklearn","[{""package"": ""imbalanced-learn"", ""version"": ""0.3.3""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'safe_indexing' from 'sklearn.utils'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'set_random_seed'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'set_random_seed'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'set_random_seed'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'set_random_seed'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.1.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'set_random_seed'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.0.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'set_random_seed'"
"sklearn.preprocessing.Imputer","sklearn","sklearn.preprocessing.Imputer","sklearn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing'"
"keras.optimizers.Adam","keras","keras.optimizers.Adam","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'Adam' from 'keras.optimizers'"
"keras.initializers.glorot_uniform","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"sklearn.preprocessing.OneHotEncoder","scikit-learn","sklearn.preprocessing.OneHotEncoder","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'categories'"
"keras.layers.Embedding","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.layers.GRU","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.layers.LSTM","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"pandas.pivot","pandas","pandas.pivot","pandas","[{""package"": ""pandas"", ""version"": ""0.23.4""}]","TypeError","TypeError: pivot_simple() got multiple values for argument 'index'"
"tqdm.notebook.tqdm","tqdm","tqdm.notebook.tqdm","tqdm","[{""package"": ""tqdm"", ""version"": ""4.60.0""}]","AttributeError","AttributeError: 'tqdm_notebook' object has no attribute 'disp'"
"sklearn.preprocessing.OrdinalEncoder","sklearn","sklearn.preprocessing.OrdinalEncoder","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","ImportError","ImportError: cannot import name 'OrdinalEncoder' from 'sklearn.preprocessing'"
"sklearn.metrics.mean_squared_error","scikit-learn","sklearn.metrics.mean_squared_error","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","TypeError","TypeError: mean_squared_error() got an unexpected keyword argument 'squared'"
"sklearn.metrics.mean_squared_error","scikit-learn","sklearn.metrics.mean_squared_error","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","TypeError","TypeError: mean_squared_error() got an unexpected keyword argument 'squared'"
"sklearn.metrics.mean_squared_error","scikit-learn","sklearn.metrics.mean_squared_error","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","TypeError","TypeError: mean_squared_error() got an unexpected keyword argument 'squared'"
"keras.utils.to_categorical","keras","keras.utils.to_categorical","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'to_categorical' from 'keras.utils'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend.tensorflow_backend.symbolic_fn_wrapper","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.backend.tensorflow_backend.symbolic_fn_wrapper","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.layers.convolutional.Conv1D","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"tensorflow.random.set_seed","tensorflow","tensorflow._api.v1.random.set_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.14.0""}]","AttributeError","AttributeError: module 'tensorflow._api.v1.random' has no attribute 'set_seed'"
"tensorflow._api.v1.random.set_seed","tensorflow","tensorflow._api.v1.random.set_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.13.1""}]","AttributeError","AttributeError: module 'tensorflow._api.v1.random' has no attribute 'set_seed'"
"statsmodels.tsa.statespace.sarimax.SARIMAX","statsmodels","pandas.Panel","pandas","[{""package"": ""statsmodels"", ""version"": ""0.9.0""}, {""package"": ""pandas"", ""version"": ""1.2.4""}]","AttributeError","AttributeError: module 'pandas' has no attribute 'Panel'"
"utils.DeepInsightTransformer","utils","utils.DeepInsightTransformer","utils","[{""package"": ""utils"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'DeepInsightTransformer' from 'utils'"
"category_encoders.CountEncoder","category_encoders","category_encoders.CountEncoder","category_encoders","[{""package"": ""category_encoders"", ""version"": ""1.3.0""}]","ImportError","ImportError: cannot import name 'CountEncoder' from 'category_encoders'"
"category_encoders.CountEncoder","category_encoders","category_encoders.CountEncoder","category_encoders","[{""package"": ""category_encoders"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'CountEncoder' from 'category_encoders'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"tensorflow_addons","tensorflow_addons","tensorflow.python.keras.engine.keras_tensor","tensorflow","[{""package"": ""tensorflow_addons"", ""version"": ""0.15.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'keras_tensor' from 'tensorflow.python.keras.engine'"
"tensorflow_addons","tensorflow_addons","tensorflow.python.keras.engine.keras_tensor","tensorflow","[{""package"": ""tensorflow_addons"", ""version"": ""0.15.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'keras_tensor' from 'tensorflow.python.keras.engine'"
"tensorflow.config.list_physical_devices","tensorflow","tensorflow._api.v1.config.list_physical_devices","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.14.0""}]","AttributeError","AttributeError: module 'tensorflow._api.v1.config' has no attribute 'list_physical_devices'"
"tensorflow.config","tensorflow","tensorflow.config","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.13.1""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'config'"
"tensorflow_addons.optimizers.RectifiedAdam","tensorflow_addons","tensorflow.python.keras.engine.keras_tensor","tensorflow","[{""package"": ""tensorflow_addons"", ""version"": ""0.15.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'keras_tensor' from 'tensorflow.python.keras.engine'"
"tensorflow_addons.optimizers.RectifiedAdam","tensorflow_addons","tensorflow.python.keras.engine.keras_tensor","tensorflow","[{""package"": ""tensorflow_addons"", ""version"": ""0.15.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'keras_tensor' from 'tensorflow.python.keras.engine'"
"keras.layers.Dense","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.layers.Dense","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.optimizers.SGD","keras","keras.optimizers.SGD","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'SGD' from 'keras.optimizers'"
"keras.engine.training.fit","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.optimizers.RMSprop","keras","keras.optimizers.RMSprop","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.optimizers' has no attribute 'RMSprop'"
"keras.optimizers.Adam","keras","keras.optimizers.Adam","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.optimizers' has no attribute 'Adam'"
"numpy.polyfit","numpy","numpy.polyfit","numpy","[{""package"": ""numpy"", ""version"": ""1.19.5""}]","TypeError","TypeError: expected non-empty vector for x"
"numpy.polyfit","numpy","numpy.polyfit","numpy","[{""package"": ""numpy"", ""version"": ""1.18.5""}]","TypeError","TypeError: expected non-empty vector for x"
"sklearn.metrics.confusion_matrix","sklearn","sklearn.metrics.plot_confusion_matrix","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","ImportError","ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics'"
"sklearn.metrics.plot_confusion_matrix","sklearn","sklearn.metrics.plot_confusion_matrix","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","ImportError","ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics'"
"sklearn.metrics.confusion_matrix","sklearn","sklearn.metrics.plot_confusion_matrix","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","ImportError","ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics'"
"sklearn.metrics.plot_confusion_matrix","sklearn","sklearn.metrics.plot_confusion_matrix","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","ImportError","ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics'"
"sklearn.metrics.confusion_matrix","sklearn","sklearn.metrics.plot_confusion_matrix","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","ImportError","ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics'"
"sklearn.metrics.plot_confusion_matrix","sklearn","sklearn.metrics.plot_confusion_matrix","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","ImportError","ImportError: cannot import name 'plot_confusion_matrix' from 'sklearn.metrics'"
"pandas","pandas","pandas._libs.groupby","pandas","[{""package"": ""pandas"", ""version"": ""1.2.4""}]","ImportError","ImportError: DLL load failed: 应用程序无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。"
"CSV","pandas","pandas._libs.groupby","pandas","[{""package"": ""pandas"", ""version"": ""1.2.4""}]","ImportError","ImportError: DLL load failed: 应用程序无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。"
"tensorflow.keras.layers.Dense","tensorflow","tensorflow._api.v2.nn.gelu","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}, {""package"": ""tensorflow_addons"", ""version"": ""0.15.0""}]","AttributeError","AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'gelu'"
"keras.layers.Input","keras","keras.layers.Input","keras","[{""package"": ""keras"", ""version"": ""2.3.1""}]","TypeError","TypeError: 'int' object is not iterable"
"keras.initializers.GlorotNormal","keras","keras.initializers.GlorotNormal","keras","[{""package"": ""keras"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'keras.initializers' has no attribute 'GlorotNormal'"
"transformers.(","transformers","transformers.EvalPrediction","transformers","[{""package"": ""transformers"", ""version"": ""2.3.0""}]","ImportError","ImportError: cannot import name 'EvalPrediction' from 'transformers'"
"transformers.(","transformers","transformers.EvalPrediction","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'EvalPrediction' from 'transformers'"
"transformers.","transformers","transformers.AutoModelForMaskedLM","transformers","[{""package"": ""transformers"", ""version"": ""2.3.0""}]","ImportError","ImportError: cannot import name 'AutoModelForMaskedLM' from 'transformers'"
"transformers.","transformers","transformers.get_cosine_schedule_with_warmup","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'get_cosine_schedule_with_warmup' from 'transformers'"
"transformers.get_cosine_schedule_with_warmup","transformers","transformers.get_cosine_schedule_with_warmup","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'get_cosine_schedule_with_warmup' from 'transformers'"
"seaborn","seaborn","scipy.linalg._flapack","scipy","[{""package"": ""seaborn"", ""version"": ""0.11.2""}, {""package"": ""scipy"", ""version"": ""1.7.3""}]","ImportError","ImportError: DLL load failed: 页面文件太小，无法完成操作。"
"tensorflow.keras.layers.experimental.preprocessing.TextVectorization","tensorflow","tensorflow.python.keras.api._v1.keras.layers.experimental","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.14.0""}]","AttributeError","AttributeError: module 'tensorflow.python.keras.api._v1.keras.layers' has no attribute 'experimental'"
"tensorflow._api.v1.keras.layers.experimental","tensorflow","tensorflow._api.v1.keras.layers.experimental","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.13.1""}]","AttributeError","AttributeError: module 'tensorflow._api.v1.keras.layers' has no attribute 'experimental'"
"nltk.corpus.stopwords.words","nltk","nltk.corpus.stopwords.words","nltk","[{""package"": ""nltk"", ""version"": ""3.6.2""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'vector_size'"
"gensim.models.KeyedVectors","gensim","._highs._highs_wrapper._highs_wrapper",,"[{""package"": ""gensim"", ""version"": ""3.7.1""}, {""package"": ""scipy"", ""version"": ""1.7.3""}]","ImportError","ImportError: DLL load failed: 应用程序无法启动，因为应用程序的并行配置不正确。有关详细信息，请参阅应用程序事件日志，或使用命令行 sxstrace.exe 工具。"
"umap.UMAP","umap","umap.UMAP","umap","[{""package"": ""umap"", ""version"": ""0.1.1""}]","ImportError","ImportError: cannot import name 'UMAP' from 'umap'"
"transformers.","transformers","transformers.get_constant_schedule_with_warmup","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'get_constant_schedule_with_warmup' from 'transformers'"
"transformers.RobertaTokenizerFast","transformers","transformers.RobertaTokenizerFast","transformers","[{""package"": ""transformers"", ""version"": ""2.3.0""}]","ImportError","ImportError: cannot import name 'RobertaTokenizerFast' from 'transformers'"
"transformers.","transformers","transformers.RobertaTokenizerFast","transformers","[{""package"": ""transformers"", ""version"": ""2.3.0""}]","ImportError","ImportError: cannot import name 'RobertaTokenizerFast' from 'transformers'"
"transformers.RobertaTokenizerFast","transformers","transformers.RobertaTokenizerFast","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'RobertaTokenizerFast' from 'transformers'"
"transformers.","transformers","transformers.RobertaTokenizerFast","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'RobertaTokenizerFast' from 'transformers'"
"tensorflow._api.v1.random.set_seed","tensorflow","tensorflow._api.v1.random.set_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.14.0""}]","AttributeError","AttributeError: module 'tensorflow._api.v1.random' has no attribute 'set_seed'"
"catboost.Pool","catboost","catboost.Pool","catboost","[{""package"": ""catboost"", ""version"": ""0.17.5""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'text_features'"
"catboost.Pool","catboost","catboost.Pool","catboost","[{""package"": ""catboost"", ""version"": ""0.16.5""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'text_features'"
"catboost.Pool","catboost","catboost.Pool","catboost","[{""package"": ""catboost"", ""version"": ""0.15.2""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'text_features'"
"catboost.Pool","catboost","catboost.Pool","catboost","[{""package"": ""catboost"", ""version"": ""0.12.2""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'text_features'"
"catboost.Pool","catboost","catboost.Pool","catboost","[{""package"": ""catboost"", ""version"": ""0.10.3""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'text_features'"
"transformers.AutoModel.from_pretrained","transformers","transformers.AutoModel.from_pretrained","transformers","[{""package"": ""transformers"", ""version"": ""2.3.0""}]","ValueError","ValueError: Can't find a vocabulary file at path 'C:\Users\Administrator\.cache\torch\transformers\e72340bed936b1ad6b5ac0fb7962338f94332b7bf345e560b609b783c9e4cd62'. To load the vocabulary from a Google pretrained model use `tokenizer = BertTokenizer.from_pretrained(PRETRAINED_MODEL_NAME)`"
"joblib.delayed","joblib","joblib.delayed","joblib","[{""package"": ""joblib"", ""version"": ""0.11""}]","AttributeError","AttributeError: Can't pickle local object 'preprocessor.<locals>.for_joblib'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.backend","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"pandas","pandas","pandas._libs.algos","pandas","[{""package"": ""pandas"", ""version"": ""1.2.4""}]","ImportError","ImportError: DLL load failed: 页面文件太小，无法完成操作。"
"pyarrow.parquet.read_table","pyarrow","pyarrow.parquet","pyarrow","[{""package"": ""pyarrow"", ""version"": ""5.0.0""}]","AttributeError","AttributeError: module 'pyarrow' has no attribute 'parquet'"
"keras.optimizers.RMSprop","keras","keras.optimizers.RMSprop","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'RMSprop' from 'keras.optimizers'"
"keras.applications.VGG16","keras","keras.applications.VGG16","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.applications' has no attribute 'VGG16'"
"keras.optimizers.SGD","keras","keras.optimizers.SGD","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.optimizers' has no attribute 'SGD'"
"keras.layers.Conv2D","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.layers.Conv2D","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.optimizers.SGD","keras","tensorflow.py_func","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'py_func'"
"keras.optimizers.SGD","keras","tensorflow.py_func","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'py_func'"
"keras.optimizers.SGD","keras","tensorflow.py_func","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'py_func'"
"keras.regularizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.optimizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.regularizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.optimizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.regularizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.optimizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.regularizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.optimizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.regularizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.optimizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.regularizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.optimizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.regularizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.optimizers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"tensorflow._api.v2.train.AdamOptimizer","tensorflow","tensorflow._api.v2.train.AdamOptimizer","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'"
"tensorflow._api.v2.train.AdamOptimizer","tensorflow","tensorflow._api.v2.train.AdamOptimizer","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'"
"tensorflow._api.v2.train.AdamOptimizer","tensorflow","tensorflow._api.v2.train.AdamOptimizer","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow._api.v2.train' has no attribute 'AdamOptimizer'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.utils.to_categorical","keras","keras.utils.to_categorical","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.utils' has no attribute 'to_categorical'"
"keras.utils.plot_model","keras","keras.utils.plot_model","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'plot_model' from 'keras.utils'"
"keras.applications.Xception","keras","keras.applications.Xception","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'Xception' from 'keras.applications'"
"tensorflow.ConfigProto","tensorflow","tensorflow.ConfigProto","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'ConfigProto'"
"tensorflow.ConfigProto","tensorflow","tensorflow.ConfigProto","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'ConfigProto'"
"tensorflow.ConfigProto","tensorflow","tensorflow.ConfigProto","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'ConfigProto'"
"tensorflow.ConfigProto","tensorflow","tensorflow.ConfigProto","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.1.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'ConfigProto'"
"tensorflow.ConfigProto","tensorflow","tensorflow.ConfigProto","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.0.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'ConfigProto'"
"keras.preprocessing.text","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.preprocessing.text","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.preprocessing.text","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.preprocessing.text","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.preprocessing.text","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.preprocessing.text","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.preprocessing.text","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"tensorflow.keras.layers.CuDNNLSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'tensorflow.keras.layers' has no attribute 'CuDNNLSTM'"
"tensorflow.keras.layers.CuDNNLSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow.keras.layers' has no attribute 'CuDNNLSTM'"
"tensorflow.keras.layers.CuDNNLSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.keras.layers' has no attribute 'CuDNNLSTM'"
"tensorflow.keras.layers.CuDNNLSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow.keras.layers' has no attribute 'CuDNNLSTM'"
"keras.engine.sequential.add","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.applications.VGG16","keras","keras.applications.VGG16","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'VGG16' from 'keras.applications'"
"keras.utils.to_categorical","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.utils.to_categorical","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.utils.to_categorical","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.utils.to_categorical","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.utils.to_categorical","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.utils.to_categorical","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.utils.to_categorical","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.engine.sequential.add","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.layers.normalization.BatchNormalization","keras","keras.layers.normalization.BatchNormalization","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'BatchNormalization' from 'keras.layers.normalization'"
"tensorflow.placeholder","tensorflow","tensorflow.placeholder","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'placeholder'"
"tensorflow.enable_eager_execution","tensorflow","tensorflow.enable_eager_execution","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'"
"tensorflow.enable_eager_execution","tensorflow","tensorflow.enable_eager_execution","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'"
"tensorflow.enable_eager_execution","tensorflow","tensorflow.enable_eager_execution","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'"
"tensorflow.enable_eager_execution","tensorflow","tensorflow.enable_eager_execution","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'"
"tensorflow.enable_eager_execution","tensorflow","tensorflow.enable_eager_execution","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.1.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'"
"tensorflow.enable_eager_execution","tensorflow","tensorflow.enable_eager_execution","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.0.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'enable_eager_execution'"
"tensorflow.keras.layers.LSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.CuDNNLSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.LSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.CuDNNLSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.LSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.CuDNNLSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.LSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.CuDNNLSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.LSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.CuDNNLSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.LSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"tensorflow.keras.layers.CuDNNLSTM","tensorflow","tensorflow.keras.layers.CuDNNLSTM","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'CuDNNLSTM' from 'tensorflow.keras.layers'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.optimizers.adam","keras","keras.optimizers.adam","keras","[{""package"": ""keras"", ""version"": ""2.4.3""}]","ImportError","ImportError: cannot import name 'adam' from 'keras.optimizers'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Input","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.load_model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.6.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"efficientnet.EfficientNetB3","efficientnet","efficientnet.EfficientNetB3","efficientnet","[{""package"": ""efficientnet"", ""version"": ""1.1.1""}]","ImportError","ImportError: cannot import name 'EfficientNetB3' from 'efficientnet'"
"efficientnet.EfficientNetB3","efficientnet","efficientnet.EfficientNetB3","efficientnet","[{""package"": ""efficientnet"", ""version"": ""1.0.0""}]","ImportError","ImportError: cannot import name 'EfficientNetB3' from 'efficientnet'"
"efficientnet.EfficientNetB3","efficientnet","keras.utils.get_file","keras","[{""package"": ""efficientnet"", ""version"": ""0.0.4""}, {""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'get_file' from 'keras.utils'"
"efficientnet.__init__.wrapper","efficientnet","keras.utils.get_file","keras","[{""package"": ""efficientnet"", ""version"": ""1.1.1""}, {""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.utils' has no attribute 'get_file'"
"efficientnet.__init__.wrapper","efficientnet","keras.utils.get_file","keras","[{""package"": ""efficientnet"", ""version"": ""1.0.0""}, {""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.utils' has no attribute 'get_file'"
"efficientnet.keras.EfficientNetB3","efficientnet","keras.utils.get_file","keras","[{""package"": ""efficientnet"", ""version"": ""0.0.4""}, {""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'get_file' from 'keras.utils'"
"efficientnet.EfficientNetB3","efficientnet","keras.utils.get_file","keras","[{""package"": ""efficientnet"", ""version"": ""1.1.1""}, {""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.utils' has no attribute 'get_file'"
"efficientnet.EfficientNetB3","efficientnet","keras.utils.get_file","keras","[{""package"": ""efficientnet"", ""version"": ""1.0.0""}, {""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.utils' has no attribute 'get_file'"
"efficientnet.EfficientNetB3","efficientnet","keras.utils.generic_utils","keras","[{""package"": ""efficientnet"", ""version"": ""1.0.0""}, {""package"": ""keras"", ""version"": ""2.4.3""}]","AttributeError","AttributeError: module 'keras.utils' has no attribute 'generic_utils'"
"efficientnet.EfficientNetB3","efficientnet","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""efficientnet"", ""version"": ""1.1.1""}, {""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"efficientnet.EfficientNetB3","efficientnet","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""efficientnet"", ""version"": ""1.0.0""}, {""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"imblearn.__init__.<module>","imblearn","keras.utils.Sequence","keras","[{""package"": ""imbalanced-learn"", ""version"": ""0.6.2""}, {""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.utils' has no attribute 'Sequence'"
"imblearn.over_sampling.RandomOverSampler","imblearn","sklearn.externals.six","sklearn","[{""package"": ""imbalanced-learn"", ""version"": ""0.4.3""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"keras.layers.SeparableConv2D","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"imblearn.over_sampling.RandomOverSampler","imblearn","sklearn.utils.safe_indexing","sklearn","[{""package"": ""imbalanced-learn"", ""version"": ""0.3.3""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'safe_indexing' from 'sklearn.utils'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'set_random_seed' from 'tensorflow'"
"keras.utils.Sequence","keras","keras.utils.Sequence","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'Sequence' from 'keras.utils'"
"keras.optimizers.Adam","keras","tensorflow.py_func","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'py_func'"
"keras.optimizers.Adam","keras","tensorflow.py_func","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'py_func'"
"keras.optimizers.Adam","keras","tensorflow.py_func","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'py_func'"
"tensorflow.python.keras.utils.to_categorical","tensorflow","tensorflow.python.keras.utils.to_categorical","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'to_categorical' from 'tensorflow.python.keras.utils'"
"tensorflow.python.keras.utils.to_categorical","tensorflow","tensorflow.python.keras.utils.to_categorical","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'to_categorical' from 'tensorflow.python.keras.utils'"
"tensorflow.python.keras.utils.to_categorical","tensorflow","tensorflow.python.keras.utils.to_categorical","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'to_categorical' from 'tensorflow.python.keras.utils'"
"tensorflow.python.keras.utils.to_categorical","tensorflow","tensorflow.python.keras.utils.to_categorical","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'to_categorical' from 'tensorflow.python.keras.utils'"
"tensorflow.python.keras.utils.to_categorical","tensorflow","tensorflow.python.keras.utils.to_categorical","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'to_categorical' from 'tensorflow.python.keras.utils'"
"scipy.ndimage.imread","scipy","scipy.ndimage.imread","scipy","[{""package"": ""scipy"", ""version"": ""1.7.3""}]","ImportError","ImportError: cannot import name 'imread' from 'scipy.ndimage'"
"keras.applications.DenseNet121","keras","keras.applications.DenseNet121","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'DenseNet121' from 'keras.applications'"
"tensorflow.reset_default_graph","tensorflow","tensorflow.reset_default_graph","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'reset_default_graph'"
"sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis","scikit-learn","sklearn.discriminant_analysis.QuadraticDiscriminantAnalysis","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: __init__() takes 1 positional argument but 2 were given"
"chainer.Sequential","chainer","chainer.Sequential","chainer","[{""package"": ""chainer"", ""version"": ""1.5.1""}]","ImportError","ImportError: cannot import name 'Sequential' from 'chainer'"
"chainer.Sequential","chainer","chainer.Sequential","chainer","[{""package"": ""chainer"", ""version"": ""1.22.0""}]","ImportError","ImportError: cannot import name 'Sequential' from 'chainer'"
"keras.layers.Embedding","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'set_random_seed' from 'tensorflow'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'set_random_seed' from 'tensorflow'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'set_random_seed' from 'tensorflow'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'set_random_seed' from 'tensorflow'"
"tensorflow.set_random_seed","tensorflow","tensorflow.set_random_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'set_random_seed' from 'tensorflow'"
"keras.constraints.max_norm","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"tensorflow.keras.metrics.auc","tensorflow","tensorflow.keras.metrics.auc","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}, {""package"": ""keras"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.keras.metrics' has no attribute 'auc'"
"keras.optimizers.Nadam","keras","keras.optimizers.Nadam","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'Nadam' from 'keras.optimizers'"
"sklearn.utils.class_weight.compute_sklearn.utils.class_weight","scikit-learn","sklearn.utils.class_weight.compute_sklearn.utils.class_weight","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: compute_class_weight() takes 1 positional argument but 3 were given"
"tensorflow.keras.initializers.random_uniform","tensorflow","tensorflow.keras.initializers.random_uniform","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'random_uniform' from 'tensorflow.keras.initializers'"
"tensorflow.keras.initializers.random_uniform","tensorflow","tensorflow.keras.initializers.random_uniform","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'random_uniform' from 'tensorflow.keras.initializers'"
"tensorflow.keras.initializers.random_uniform","tensorflow","tensorflow.keras.initializers.random_uniform","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'random_uniform' from 'tensorflow.keras.initializers'"
"keras.models.Model","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.layers.Dense","keras","keras.layers.Dense","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","TypeError","TypeError: __init__() missing 1 required positional argument: 'units'"
"keras.engine.training.fit_generator","keras","cv2.morphologyEx","opencv-python","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""opencv-python"", ""version"": ""4.3.0.36""}]","TypeError","TypeError: Expected Ptr<cv::UMat> for argument 'src'"
"keras.engine.training.fit_generator","keras","cv2.morphologyEx","opencv-python","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""opencv-python"", ""version"": ""4.2.0.34""}]","TypeError","TypeError: Expected Ptr<cv::UMat> for argument 'src'"
"keras.engine.training.fit_generator","keras","cv2.morphologyEx","opencv-python","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""opencv-python"", ""version"": ""4.1.2.30""}]","TypeError","TypeError: Expected Ptr<cv::UMat> for argument '%s'"
"keras.engine.training.fit_generator","keras","cv2.morphologyEx","opencv-python","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""opencv-python"", ""version"": ""4.1.1.26""}]","TypeError","TypeError: Expected Ptr<cv::UMat> for argument '%s'"
"keras.engine.training.fit_generator","keras","cv2.morphologyEx","opencv-python","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""opencv-python"", ""version"": ""4.1.0.25""}]","TypeError","TypeError: Expected cv::UMat for argument 'src'"
"keras.engine.training.fit_generator","keras","cv2.morphologyEx","opencv-python","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""opencv-python"", ""version"": ""4.0.0.21""}]","TypeError","TypeError: Expected cv::UMat for argument 'src'"
"tensorflow.placeholder","tensorflow","tensorflow.placeholder","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'placeholder'"
"tensorflow.placeholder","tensorflow","tensorflow.placeholder","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'placeholder'"
"tensorflow.placeholder","tensorflow","tensorflow.placeholder","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'placeholder'"
"keras.preprocessing.image.image","keras","keras.preprocessing.image.image","keras","[{""package"": ""keras"", ""version"": ""2.4.3""}]","ImportError","ImportError: cannot import name 'image' from 'keras.preprocessing.image'"
"keras.applications.DenseNet169","keras","keras.applications.DenseNet169","keras","[{""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'DenseNet169' from 'keras.applications'"
"imblearn.over_sampling.RandomOverSampler","imbalanced-learn","imblearn.over_sampling.RandomOverSampler","imbalanced-learn","[{""package"": ""imbalanced-learn"", ""version"": ""0.6.2""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'ratio'"
"category_encoders.CountEncoder","category_encoders","category_encoders.CountEncoder","category_encoders","[{""package"": ""category_encoders"", ""version"": ""1.3.0""}]","AttributeError","AttributeError: module 'category_encoders' has no attribute 'CountEncoder'"
"category_encoders.CountEncoder","category_encoders","category_encoders.CountEncoder","category_encoders","[{""package"": ""category_encoders"", ""version"": ""2.0.0""}]","AttributeError","AttributeError: module 'category_encoders' has no attribute 'CountEncoder'"
"sklearn.preprocessing.OneHotEncoder","scikit-learn","sklearn.preprocessing.OneHotEncoder","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'drop'"
"sklearn.preprocessing.OneHotEncoder","scikit-learn","sklearn.preprocessing.OneHotEncoder","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'drop'"
"matplotlib.pyplot.plot","matplotlib","matplotlib.pyplot.plot","matplotlib","[{""package"": ""matplotlib"", ""version"": ""3.3.4""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'l1_ratio'"
"keras.engine.training.fit","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"tensorflow.keras.metrics.AUC","tensorflow","tensorflow.keras.metrics.AUC","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.13.1""}]","AttributeError","AttributeError: module 'tensorflow.keras.metrics' has no attribute 'AUC'"
"efficientnet.keras.EfficientNetB3","efficientnet","keras.utils.get_file","keras","[{""package"": ""efficientnet"", ""version"": ""1.1.1""}, {""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.utils' has no attribute 'get_file'"
"efficientnet.keras.EfficientNetB3","efficientnet","keras.utils.get_file","keras","[{""package"": ""efficientnet"", ""version"": ""1.0.0""}, {""package"": ""keras"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'keras.utils' has no attribute 'get_file'"
"efficientnet","efficientnet","keras.utils.get_file","keras","[{""package"": ""efficientnet"", ""version"": ""0.0.4""}, {""package"": ""keras"", ""version"": ""2.7.0""}]","ImportError","ImportError: cannot import name 'get_file' from 'keras.utils'"
"efficientnet.keras.EfficientNetB3","efficientnet","keras.utils.generic_utils","keras","[{""package"": ""efficientnet"", ""version"": ""1.0.0""}, {""package"": ""keras"", ""version"": ""2.4.3""}]","AttributeError","AttributeError: module 'keras.utils' has no attribute 'generic_utils'"
"efficientnet.keras.EfficientNetB3","efficientnet","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""efficientnet"", ""version"": ""1.1.1""}, {""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"efficientnet.keras.EfficientNetB3","efficientnet","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""efficientnet"", ""version"": ""1.0.0""}, {""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.layers.convolutional.Conv2D","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.layers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.layers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.layers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.layers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.layers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.layers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.layers","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.7.0""}, {""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.utils.np_utils","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.4.3""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.utils.np_utils","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.4.3""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.regularizers.l2","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.4.3""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.layers.Input","keras","tensorflow.placeholder","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow' has no attribute 'placeholder'"
"keras.utils.np_utils","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.utils.np_utils","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.4.3""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"chainer.datasets","chainer","chainer.datasets","chainer","[{""package"": ""chainer"", ""version"": ""1.5.1""}]","AttributeError","AttributeError: module 'chainer' has no attribute 'datasets'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.4.3""}, {""package"": ""tensorflow"", ""version"": ""2.4.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.4.3""}, {""package"": ""tensorflow"", ""version"": ""2.3.1""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.engine.sequential.add","keras","tensorflow.python.framework.ops._TensorLike","tensorflow","[{""package"": ""keras"", ""version"": ""2.4.3""}, {""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow.python.framework.ops' has no attribute '_TensorLike'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.3.1""}, {""package"": ""tensorflow"", ""version"": ""2.1.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"keras.models.Sequential","keras","tensorflow.python.eager.context.get_config","tensorflow","[{""package"": ""keras"", ""version"": ""2.4.3""}, {""package"": ""tensorflow"", ""version"": ""2.0.0""}]","ImportError","ImportError: cannot import name 'get_config' from 'tensorflow.python.eager.context'"
"sklearn.preprocessing.MinMaxScaler","scikit-learn","sklearn.preprocessing.MinMaxScaler","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: __init__() takes from 1 to 2 positional arguments but 3 were given"
"gensim.models.phrases.Phrases","gensim","gensim.models.phrases.Phrases","gensim","[{""package"": ""gensim"", ""version"": ""4.0.1""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'common_terms'"
"contractions.CONTRACTION_MAP","contractions","contractions.CONTRACTION_MAP","contractions","[{""package"": ""contractions"", ""version"": ""0.0.58""}]","ImportError","ImportError: cannot import name 'CONTRACTION_MAP' from 'contractions'"
"transformers.T5ForConditionalGeneration","transformers","transformers.T5ForConditionalGeneration","transformers","[{""package"": ""transformers"", ""version"": ""2.3.0""}]","ImportError","ImportError: cannot import name 'T5ForConditionalGeneration' from 'transformers'"
"transformers.T5Tokenizer","transformers","transformers.T5Tokenizer","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'T5Tokenizer' from 'transformers'"
"transformers.ElectraTokenizer","transformers","transformers.ElectraTokenizer","transformers","[{""package"": ""transformers"", ""version"": ""2.3.0""}]","ImportError","ImportError: cannot import name 'ElectraTokenizer' from 'transformers'"
"transformers.ElectraTokenizer","transformers","transformers.ElectraTokenizer","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'ElectraTokenizer' from 'transformers'"
"sklearn.preprocessing.OrdinalEncoder","scikit-learn","sklearn.preprocessing.OrdinalEncoder","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given"
"sklearn.model_selection.KFold","scikit-learn","sklearn.model_selection.KFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: __init__() takes from 1 to 2 positional arguments but 4 were given"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: split() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","TypeError","TypeError: split() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","TypeError","TypeError: split() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.22""}]","TypeError","TypeError: split() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.22.1""}]","TypeError","TypeError: split() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.23.2""}]","TypeError","TypeError: split() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.24.2""}]","TypeError","TypeError: split() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.22""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.22.1""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'shuffle'"
"sklearn.model_selection.StratifiedKFold","scikit-learn","sklearn.model_selection.StratifiedKFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'shuffle'"
"sklearn.naive_bayes.CategoricalNB","sklearn","sklearn.naive_bayes.CategoricalNB","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","ImportError","ImportError: cannot import name 'CategoricalNB' from 'sklearn.naive_bayes'"
"sklearn.naive_bayes.CategoricalNB","sklearn","sklearn.naive_bayes.CategoricalNB","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","ImportError","ImportError: cannot import name 'CategoricalNB' from 'sklearn.naive_bayes'"
"sklearn.metrics.plot_roc_curve","sklearn","sklearn.metrics.plot_roc_curve","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","ImportError","ImportError: cannot import name 'plot_roc_curve' from 'sklearn.metrics'"
"sklearn.metrics.plot_roc_curve","sklearn","sklearn.metrics.plot_roc_curve","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","ImportError","ImportError: cannot import name 'plot_roc_curve' from 'sklearn.metrics'"
"sklearn.preprocessing.Imputer","sklearn","sklearn.preprocessing.Imputer","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.22""}]","ImportError","ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing'"
"sklearn.preprocessing.Imputer","sklearn","sklearn.preprocessing.Imputer","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.22.1""}]","ImportError","ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing'"
"sklearn.preprocessing.Imputer","sklearn","sklearn.preprocessing.Imputer","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.23.2""}]","ImportError","ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing'"
"sklearn.preprocessing.Imputer","sklearn","sklearn.preprocessing.Imputer","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.24.2""}]","ImportError","ImportError: cannot import name 'Imputer' from 'sklearn.preprocessing'"
"nltk.corpus.stopwords.words","nltk","nltk.corpus.stopwords.words","nltk","[{""package"": ""nltk"", ""version"": ""3.6.2""}]","TypeError","TypeError: sequence item 0: expected str instance, float found"
"tensorflow.keras.layers.TextVectorization","tensorflow","tensorflow.keras.layers.TextVectorization","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.4.1""}]","AttributeError","AttributeError: module 'tensorflow.keras.layers' has no attribute 'TextVectorization'"
"tensorflow.keras.layers.TextVectorization","tensorflow","tensorflow.keras.layers.TextVectorization","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow.keras.layers' has no attribute 'TextVectorization'"
"tensorflow.keras.layers.TextVectorization","tensorflow","tensorflow.keras.layers.TextVectorization","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow.keras.layers' has no attribute 'TextVectorization'"
"tensorflow.keras.layers.TextVectorization","tensorflow","tensorflow.python.keras.api._v1.keras.layers.TextVectorization","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.14.0""}]","AttributeError","AttributeError: module 'tensorflow.python.keras.api._v1.keras.layers' has no attribute 'TextVectorization'"
"tensorflow._api.v1.keras.layers.TextVectorization","tensorflow","tensorflow._api.v1.keras.layers.TextVectorization","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.13.1""}]","AttributeError","AttributeError: module 'tensorflow._api.v1.keras.layers' has no attribute 'TextVectorization'"
"sklearn.naive_bayes.ComplementNB","sklearn","sklearn.naive_bayes.ComplementNB","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","ImportError","ImportError: cannot import name 'ComplementNB' from 'sklearn.naive_bayes'"
"transformers.get_linear_schedule_with_warmup","transformers","transformers.get_linear_schedule_with_warmup","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'get_linear_schedule_with_warmup' from 'transformers'"
"sklearn.utils.class_weight.compute_class_weight","scikit-learn","sklearn.utils.class_weight.compute_class_weight","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: compute_class_weight() takes 1 positional argument but 3 were given"
"tensorflow._api.v2.nn.gelu","tensorflow","tensorflow._api.v2.nn.gelu","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'gelu'"
"tensorflow._api.v2.nn.gelu","tensorflow","tensorflow._api.v2.nn.gelu","tensorflow","[{""package"": ""tensorflow"", ""version"": ""2.2.0""}]","AttributeError","AttributeError: module 'tensorflow._api.v2.nn' has no attribute 'gelu'"
"tensorflow.nn.gelu","tensorflow","tensorflow._api.v1.nn.gelu","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.14.0""}]","AttributeError","AttributeError: module 'tensorflow._api.v1.nn' has no attribute 'gelu'"
"tensorflow._api.v1.keras.layers.LayerNormalization","tensorflow","tensorflow._api.v1.keras.layers.LayerNormalization","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.13.1""}]","AttributeError","AttributeError: module 'tensorflow._api.v1.keras.layers' has no attribute 'LayerNormalization'"
"transformers.","transformers","transformers.get_scheduler","transformers","[{""package"": ""transformers"", ""version"": ""2.3.0""}]","ImportError","ImportError: cannot import name 'get_scheduler' from 'transformers'"
"transformers.","transformers","transformers.get_scheduler","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'get_scheduler' from 'transformers'"
"transformers.DistilBertTokenizerFast","transformers","transformers.DistilBertTokenizerFast","transformers","[{""package"": ""transformers"", ""version"": ""2.3.0""}]","ImportError","ImportError: cannot import name 'DistilBertTokenizerFast' from 'transformers'"
"transformers.DistilBertTokenizerFast","transformers","transformers.DistilBertTokenizerFast","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'DistilBertTokenizerFast' from 'transformers'"
"mlxtend.classifier.StackingCVClassifier","mlxtend","sklearn.externals.six","sklearn","[{""package"": ""mlxtend"", ""version"": ""0.7.0""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"mlxtend.classifier.StackingCVClassifier","mlxtend","sklearn.externals.six","sklearn","[{""package"": ""mlxtend"", ""version"": ""0.15.0.0""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"mlxtend.classifier.StackingCVClassifier","mlxtend","sklearn.externals.six","sklearn","[{""package"": ""mlxtend"", ""version"": ""0.14.0""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"mlxtend.classifier.StackingCVClassifier","mlxtend","sklearn.externals.six","sklearn","[{""package"": ""mlxtend"", ""version"": ""0.13.0""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"mlxtend.classifier.StackingCVClassifier","mlxtend","sklearn.externals.six","sklearn","[{""package"": ""mlxtend"", ""version"": ""0.12.0""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"mlxtend.classifier.StackingCVClassifier","mlxtend","sklearn.externals.six","sklearn","[{""package"": ""mlxtend"", ""version"": ""0.10.0""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"gensim.models.Word2Vec","gensim","gensim.models.Word2Vec","gensim","[{""package"": ""gensim"", ""version"": ""4.0.1""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'size'"
"sklearn.naive_bayes.MultinomialNB","scikit-learn","sklearn.naive_bayes.MultinomialNB","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: __init__() takes 1 positional argument but 2 were given"
"transformers.Trainer","transformers","transformers.Trainer","transformers","[{""package"": ""transformers"", ""version"": ""2.3.0""}]","ImportError","ImportError: cannot import name 'Trainer' from 'transformers'"
"transformers.Trainer","transformers","transformers.Trainer","transformers","[{""package"": ""transformers"", ""version"": ""2.1.1""}]","ImportError","ImportError: cannot import name 'Trainer' from 'transformers'"
"sklearn.svm.SVC","scikit-learn","sklearn.svm.SVC","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: __init__() takes 1 positional argument but 2 positional arguments (and 1 keyword-only argument) were given"
"spacy.lang.en.stop_words.STOP_WORDS.add","spacy","spacy.lang.en.stop_words.STOP_WORDS.add","spacy","[{""package"": ""spacy"", ""version"": ""3.0.6""}]","TypeError","TypeError: add() takes exactly 2 positional arguments (3 given)"
"pymc3.__init__.<module>","pymc3","arviz.geweke","arviz","[{""package"": ""pymc3"", ""version"": ""3.9.3""}, {""package"": ""arviz"", ""version"": ""0.11.4""}]","AttributeError","AttributeError: module 'arviz' has no attribute 'geweke'"
"pymc3.__init__.<module>","pymc3","arviz.geweke","arviz","[{""package"": ""pymc3"", ""version"": ""3.8""}, {""package"": ""arviz"", ""version"": ""0.11.4""}]","AttributeError","AttributeError: module 'arviz' has no attribute 'geweke'"
"sklearn.ensemble.VotingRegressor","sklearn","sklearn.ensemble.VotingRegressor","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","ImportError","ImportError: cannot import name 'VotingRegressor' from 'sklearn.ensemble'"
"sklearn.ensemble.VotingRegressor","sklearn","sklearn.ensemble.VotingRegressor","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","ImportError","ImportError: cannot import name 'VotingRegressor' from 'sklearn.ensemble'"
"catboost.CatBoostRegressor","catboost",".._catboost",,"[{""package"": ""catboost"", ""version"": ""0.15.2""}]","ImportError","ImportError: DLL load failed: 页面文件太小，无法完成操作。"
"catboost.CatBoostRegressor","catboost",".._catboost",,"[{""package"": ""catboost"", ""version"": ""0.23.2""}]","ImportError","ImportError: DLL load failed: 页面文件太小，无法完成操作。"
"sklearn.ensemble.StackingRegressor","sklearn","sklearn.ensemble.StackingRegressor","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","ImportError","ImportError: cannot import name 'StackingRegressor' from 'sklearn.ensemble'"
"sklearn.ensemble.StackingRegressor","sklearn","sklearn.ensemble.StackingRegressor","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","ImportError","ImportError: cannot import name 'StackingRegressor' from 'sklearn.ensemble'"
"sklearn.ensemble.StackingRegressor","sklearn","sklearn.ensemble.StackingRegressor","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","ImportError","ImportError: cannot import name 'StackingRegressor' from 'sklearn.ensemble'"
"catboost.CatBoostRegressor","catboost","catboost.CatBoostRegressor","catboost","[{""package"": ""catboost"", ""version"": ""0.12.2""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'min_data_in_leaf'"
"catboost.CatBoostRegressor","catboost","catboost.CatBoostRegressor","catboost","[{""package"": ""catboost"", ""version"": ""0.10.3""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'min_data_in_leaf'"
"sklearn.metrics.plot_roc_curve","sklearn","sklearn.metrics.plot_roc_curve","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","ImportError","ImportError: cannot import name 'plot_roc_curve' from 'sklearn.metrics'"
"optuna.study._optimize._run_trial","optuna","sklearn.metrics.mean_squared_error","scikit-learn","[{""package"": ""optuna"", ""version"": ""2.10.0""}, {""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","TypeError","TypeError: mean_squared_error() got an unexpected keyword argument 'squared'"
"optuna.study.study.optimize","optuna","sklearn.metrics.mean_squared_error","scikit-learn","[{""package"": ""optuna"", ""version"": ""2.10.0""}, {""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","TypeError","TypeError: mean_squared_error() got an unexpected keyword argument 'squared'"
"optuna.study._optimize._run_trial","optuna","sklearn.metrics.mean_squared_error","scikit-learn","[{""package"": ""optuna"", ""version"": ""2.10.0""}, {""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","TypeError","TypeError: mean_squared_error() got an unexpected keyword argument 'squared'"
"optuna.study.study.optimize","optuna","sklearn.metrics.mean_squared_error","scikit-learn","[{""package"": ""optuna"", ""version"": ""2.10.0""}, {""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","TypeError","TypeError: mean_squared_error() got an unexpected keyword argument 'squared'"
"optuna.study._optimize._run_trial","optuna","sklearn.metrics.mean_squared_error","scikit-learn","[{""package"": ""optuna"", ""version"": ""2.10.0""}, {""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","TypeError","TypeError: mean_squared_error() got an unexpected keyword argument 'squared'"
"optuna.study.study.optimize","optuna","sklearn.metrics.mean_squared_error","scikit-learn","[{""package"": ""optuna"", ""version"": ""2.10.0""}, {""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","TypeError","TypeError: mean_squared_error() got an unexpected keyword argument 'squared'"
"optuna.integration.lightgbm.Dataset","optuna","optuna.integration.lightgbm.Dataset","optuna","[{""package"": ""optuna"", ""version"": ""2.10.0""}]","AttributeError","AttributeError: module 'optuna.integration.lightgbm' has no attribute 'Dataset'"
"optuna.integration.lightgbm.Dataset","optuna","optuna.integration.lightgbm.Dataset","optuna","[{""package"": ""optuna"", ""version"": ""2.9.1""}]","AttributeError","AttributeError: module 'optuna.integration.lightgbm' has no attribute 'Dataset'"
"optuna.integration.lightgbm.Dataset","optuna","optuna.integration.lightgbm.Dataset","optuna","[{""package"": ""optuna"", ""version"": ""2.8.0""}]","AttributeError","AttributeError: module 'optuna.integration.lightgbm' has no attribute 'Dataset'"
"optuna.integration.lightgbm.Dataset","optuna","optuna.integration.lightgbm.Dataset","optuna","[{""package"": ""optuna"", ""version"": ""2.7.0""}]","AttributeError","AttributeError: module 'optuna.integration.lightgbm' has no attribute 'Dataset'"
"optuna.integration.lightgbm.Dataset","optuna","optuna.integration.lightgbm.Dataset","optuna","[{""package"": ""optuna"", ""version"": ""2.6.0""}]","AttributeError","AttributeError: module 'optuna.integration.lightgbm' has no attribute 'Dataset'"
"optuna.integration.lightgbm.Dataset","optuna","optuna.integration.lightgbm.Dataset","optuna","[{""package"": ""optuna"", ""version"": ""2.5.0""}]","AttributeError","AttributeError: module 'optuna.integration.lightgbm' has no attribute 'Dataset'"
"optuna.integration.lightgbm.Dataset","optuna","optuna.integration.lightgbm.Dataset","optuna","[{""package"": ""optuna"", ""version"": ""2.4.0""}]","AttributeError","AttributeError: module 'optuna.integration.lightgbm' has no attribute 'Dataset'"
"optuna.integration.lightgbm.Dataset","optuna","optuna.integration.lightgbm.Dataset","optuna","[{""package"": ""optuna"", ""version"": ""2.3.0""}]","AttributeError","AttributeError: module 'optuna.integration.lightgbm' has no attribute 'Dataset'"
"sklearn.model_selection.KFold","scikit-learn","sklearn.model_selection.KFold","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: __init__() takes from 1 to 2 positional arguments but 3 positional arguments (and 1 keyword-only argument) were given"
"category_encoders.james_stein","category_encoders","category_encoders.james_stein","category_encoders","[{""package"": ""category_encoders"", ""version"": ""1.3.0""}]","AttributeError","AttributeError: module 'category_encoders' has no attribute 'james_stein'"
"category_encoders.CatBoostEncoder","category_encoders","category_encoders.CatBoostEncoder","category_encoders","[{""package"": ""category_encoders"", ""version"": ""1.3.0""}]","AttributeError","AttributeError: module 'category_encoders' has no attribute 'CatBoostEncoder'"
"catboost.CatBoostClassifier","catboost","catboost.CatBoostClassifier","catboost","[{""package"": ""catboost"", ""version"": ""0.12.2""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'min_data_in_leaf'"
"catboost.CatBoostClassifier","catboost","catboost.CatBoostClassifier","catboost","[{""package"": ""catboost"", ""version"": ""0.10.3""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'min_data_in_leaf'"
"imblearn.pipeline.Pipeline","imblearn","sklearn.externals.six","sklearn","[{""package"": ""imbalanced-learn"", ""version"": ""0.4.3""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"imblearn.pipeline.Pipeline","imblearn","sklearn.externals.six","sklearn","[{""package"": ""imbalanced-learn"", ""version"": ""0.3.3""}, {""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"optuna.study._optimize._run_trial","optuna","catboost.CatBoostClassifier","catboost","[{""package"": ""optuna"", ""version"": ""2.10.0""}, {""package"": ""catboost"", ""version"": ""0.12.2""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'min_data_in_leaf'"
"optuna.study.study.optimize","optuna","catboost.CatBoostClassifier","catboost","[{""package"": ""optuna"", ""version"": ""2.10.0""}, {""package"": ""catboost"", ""version"": ""0.12.2""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'min_data_in_leaf'"
"optuna.study._optimize._run_trial","optuna","catboost.CatBoostClassifier","catboost","[{""package"": ""optuna"", ""version"": ""2.10.0""}, {""package"": ""catboost"", ""version"": ""0.10.3""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'min_data_in_leaf'"
"optuna.study.study.optimize","optuna","catboost.CatBoostClassifier","catboost","[{""package"": ""optuna"", ""version"": ""2.10.0""}, {""package"": ""catboost"", ""version"": ""0.10.3""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'min_data_in_leaf'"
"eli5.show_weights","eli5","eli5.show_weights","eli5","[{""package"": ""eli5"", ""version"": ""0.11.0""}]","AttributeError","AttributeError: module 'eli5' has no attribute 'show_weights'"
"sklearn.ensemble.HistGradientBoostingClassifier","sklearn","sklearn.ensemble.HistGradientBoostingClassifier","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.24.2""}]","ImportError","ImportError: cannot import name 'HistGradientBoostingClassifier' from 'sklearn.ensemble'"
"sklearn.impute.KNNImputer","sklearn","sklearn.impute.KNNImputer","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","ImportError","ImportError: cannot import name 'KNNImputer' from 'sklearn.impute'"
"sklearn.impute.KNNImputer","sklearn","sklearn.impute.KNNImputer","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","ImportError","ImportError: cannot import name 'KNNImputer' from 'sklearn.impute'"
"sklearn.ensemble.GradientBoostingClassifier","scikit-learn","sklearn.ensemble.GradientBoostingClassifier","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""1.0.1""}]","TypeError","TypeError: __init__() got an unexpected keyword argument 'min_impurity_split'"
"matplotlib.pyplot.show","matplotlib","matplotlib.pyplot.show","matplotlib","[{""package"": ""matplotlib"", ""version"": ""3.3.4""}]","TypeError","TypeError: info() got an unexpected keyword argument 'show_counts'"
"sklearn.experimental.enable_halving_search_cv","sklearn","sklearn.experimental.enable_halving_search_cv","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.23.2""}]","ImportError","ImportError: cannot import name 'enable_halving_search_cv' from 'sklearn.experimental'"
"sklearn.experimental.enable_halving_search_cv","sklearn","sklearn.experimental.enable_halving_search_cv","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.22.1""}]","ImportError","ImportError: cannot import name 'enable_halving_search_cv' from 'sklearn.experimental'"
"sklearn.experimental.enable_halving_search_cv","sklearn","sklearn.experimental.enable_halving_search_cv","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.22""}]","ImportError","ImportError: cannot import name 'enable_halving_search_cv' from 'sklearn.experimental'"
"sklearn.experimental.enable_halving_search_cv","sklearn","sklearn.experimental.enable_halving_search_cv","sklearn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","ImportError","ImportError: cannot import name 'enable_halving_search_cv' from 'sklearn.experimental'"
"catboost.CatBoostClassifier","catboost",".._catboost",,"[{""package"": ""catboost"", ""version"": ""0.23.2""}]","ImportError","ImportError: DLL load failed: 页面文件太小，无法完成操作。"
"catboost.CatBoostClassifier","catboost",".._catboost",,"[{""package"": ""catboost"", ""version"": ""0.15.2""}]","ImportError","ImportError: DLL load failed: 页面文件太小，无法完成操作。"
"catboost.CatBoostClassifier","catboost",".._catboost",,"[{""package"": ""catboost"", ""version"": ""1.0.3""}]","ImportError","ImportError: DLL load failed: 页面文件太小，无法完成操作。"
"imblearn.over_sampling.SMOTE","imblearn","sklearn.externals.six","sklearn","[{""package"": ""imbalanced-learn"", ""version"": ""0.4.3""}, {""package"": ""scikit-learn"", ""version"": ""0.24.2""}]","ImportError","ImportError: cannot import name 'six' from 'sklearn.externals'"
"imblearn.over_sampling.SMOTE","imblearn","sklearn.utils.safe_indexing","sklearn","[{""package"": ""imbalanced-learn"", ""version"": ""0.3.3""}, {""package"": ""scikit-learn"", ""version"": ""0.24.2""}]","ImportError","ImportError: cannot import name 'safe_indexing' from 'sklearn.utils'"
"tensorflow.keras.losses.SparseCategoricalCrossentropy","tensorflow","tensorflow.keras.losses.SparseCategoricalCrossentropy","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.13.1""}]","ImportError","ImportError: cannot import name 'SparseCategoricalCrossentropy' from 'tensorflow.keras.losses'"
"sklearn.metrics.roc_auc_score","scikit-learn","sklearn.metrics.roc_auc_score","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.21.3""}]","TypeError","TypeError: roc_auc_score() got an unexpected keyword argument 'multi_class'"
"sklearn.metrics.roc_auc_score","scikit-learn","sklearn.metrics.roc_auc_score","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.20.3""}]","TypeError","TypeError: roc_auc_score() got an unexpected keyword argument 'multi_class'"
"sklearn.metrics.roc_auc_score","scikit-learn","sklearn.metrics.roc_auc_score","scikit-learn","[{""package"": ""scikit-learn"", ""version"": ""0.19.2""}]","TypeError","TypeError: roc_auc_score() got an unexpected keyword argument 'multi_class'"
"tensorflow.random.set_seed","tensorflow","tensorflow.random.set_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.15.2""}]","ImportError","ImportError: cannot import name 'set_seed' from 'tensorflow.random'"
"tensorflow.random.set_seed","tensorflow","tensorflow.random.set_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.14.0""}]","ImportError","ImportError: cannot import name 'set_seed' from 'tensorflow.random'"
"tensorflow.random.set_seed","tensorflow","tensorflow.random.set_seed","tensorflow","[{""package"": ""tensorflow"", ""version"": ""1.13.1""}]","ImportError","ImportError: cannot import name 'set_seed' from 'tensorflow.random'"
"ggplot.__init__.<module>","ggplot","pandas.tslib","pandas","[{""package"": ""ggplot"", ""version"": ""0.11.5""}, {""package"": ""pandas"", ""version"": ""1.2.4""}]","AttributeError","AttributeError: module 'pandas' has no attribute 'tslib'"
"lightgbm.log_evaluation","lightgbm","lightgbm.log_evaluation","lightgbm","[{""package"": ""lightgbm"", ""version"": ""3.2.1""}]","AttributeError","AttributeError: module 'lightgbm' has no attribute 'log_evaluation'"
"lightgbm.log_evaluation","lightgbm","lightgbm.log_evaluation","lightgbm","[{""package"": ""lightgbm"", ""version"": ""3.1.1""}]","AttributeError","AttributeError: module 'lightgbm' has no attribute 'log_evaluation'"
"lightgbm.log_evaluation","lightgbm","lightgbm.log_evaluation","lightgbm","[{""package"": ""lightgbm"", ""version"": ""3.0.0""}]","AttributeError","AttributeError: module 'lightgbm' has no attribute 'log_evaluation'"
"lightgbm.log_evaluation","lightgbm","lightgbm.log_evaluation","lightgbm","[{""package"": ""lightgbm"", ""version"": ""2.3.1""}]","AttributeError","AttributeError: module 'lightgbm' has no attribute 'log_evaluation'"
"lightgbm.log_evaluation","lightgbm","lightgbm.log_evaluation","lightgbm","[{""package"": ""lightgbm"", ""version"": ""2.2.3""}]","AttributeError","AttributeError: module 'lightgbm' has no attribute 'log_evaluation'"
"lightgbm.log_evaluation","lightgbm","lightgbm.log_evaluation","lightgbm","[{""package"": ""lightgbm"", ""version"": ""2.1.2""}]","AttributeError","AttributeError: module 'lightgbm' has no attribute 'log_evaluation'"
